axis_linear: 1
scale_linear: 300
scale_linear_turbo: 400

axis_angular: 2
scale_angular: 80
scale_angular_turbo: 600


enable_button: 5  # L2 shoulder button
enable_turbo_button: 6  # L1 shoulder button
